// Export PDF du bilan patrimonial — utilise jsPDF chargé en CDN à la volée.
// Layout simple sans dépendance à html2canvas pour rester léger.

let _jspdfLoaded = false;
async function ensureJsPDF() {
  if (_jspdfLoaded && window.jspdf) return window.jspdf;
  if (window.jspdf) { _jspdfLoaded = true; return window.jspdf; }
  await new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = 'https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js';
    s.onload = resolve;
    s.onerror = () => reject(new Error('Failed to load jsPDF from CDN'));
    document.head.appendChild(s);
  });
  _jspdfLoaded = true;
  return window.jspdf;
}

function fmtNum(n) {
  return Math.round(Number(n) || 0).toLocaleString('fr-FR');
}

export async function exportWealthPDF({ holdings, totals, locale = 'fr' } = {}) {
  const isEN = locale === 'en';
  const { jsPDF } = await ensureJsPDF();
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const margin = 15;
  let y = margin;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text(isEN ? 'Wealth Report' : 'Bilan patrimonial', margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(isEN ? `Generated by Alpha on ${new Date().toLocaleDateString('en-US')}` : `Généré par Alpha le ${new Date().toLocaleDateString('fr-FR')}`, margin, y);
  y += 10;

  // Total
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(isEN ? `Total wealth: ${fmtNum(totals.total)} €` : `Patrimoine total : ${fmtNum(totals.total)} €`, margin, y);
  y += 8;

  // Allocation par catégorie
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(isEN ? 'Allocation by category' : 'Répartition par catégorie', margin, y);
  y += 6;
  const { WEALTH_CATEGORIES } = await import('./wealth.js');
  doc.setFontSize(10);
  for (const cat of WEALTH_CATEGORIES) {
    const v = totals.byCategory[cat.id];
    if (!v) continue;
    const pct = (v / totals.total * 100).toFixed(1);
    doc.text(`${cat.label} : ${fmtNum(v)} €  (${pct}%)`, margin + 5, y);
    y += 5;
  }
  y += 5;

  // Détail par holding
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(isEN ? 'Holdings detail' : 'Détail des positions', margin, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0);

  // Header table
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y - 4, 180, 6, 'F');
  doc.text(isEN ? 'Name' : 'Nom', margin + 1, y);
  doc.text('Ticker', margin + 60, y);
  doc.text(isEN ? 'Account' : 'Compte', margin + 85, y);
  doc.text(isEN ? 'Qty' : 'Qté', margin + 130, y, { align: 'right' });
  doc.text(isEN ? 'Value €' : 'Valeur €', margin + 175, y, { align: 'right' });
  y += 5;

  const sorted = (holdings || []).slice().sort((a, b) => (b.value || 0) - (a.value || 0));
  for (const h of sorted) {
    if (y > 280) { doc.addPage(); y = margin; }
    doc.text(String(h.name || '').slice(0, 40), margin + 1, y);
    doc.text(String(h.ticker || ''), margin + 60, y);
    doc.text(String(h.account || '').slice(0, 25), margin + 85, y);
    doc.text(String(h.quantity || ''), margin + 130, y, { align: 'right' });
    doc.text(fmtNum(h.value || 0), margin + 175, y, { align: 'right' });
    y += 4.5;
  }

  // Real-estate dedicated section if any
  const properties = (holdings || []).filter(h => h.category === 'real_estate' && (h.loans || h.loanAmount));
  if (properties.length > 0) {
    if (y > 250) { doc.addPage(); y = margin; }
    y += 4;
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    doc.text(isEN ? 'Real estate detail' : 'Détail immobilier', margin, y);
    y += 7;
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    const { computeRealEstateMetrics, fmtMonths } = await import('./real-estate.js');
    for (const h of properties) {
      const m = computeRealEstateMetrics(h);
      if (y > 270) { doc.addPage(); y = margin; }
      doc.setFont(undefined, 'bold');
      doc.text(String(h.name), margin, y);
      doc.setFont(undefined, 'normal');
      y += 5;
      doc.setFontSize(8);
      const lines = [
        `${isEN ? 'Type' : 'Type'} : ${h.propertyType || 'N/A'}`,
        `${isEN ? 'Current value' : 'Valeur'} : ${fmtNum(m.currentValue)} €  ·  ${isEN ? 'Purchase' : 'Achat'} : ${fmtNum(h.purchasePrice || 0)} €`,
        `${isEN ? 'Monthly payment' : 'Mensualité'} : ${fmtNum(m.monthlyPayment)} €  ·  ${isEN ? 'Remaining' : 'Capital restant'} : ${fmtNum(m.remaining)} €  ·  LTV : ${m.ltv.toFixed(1)}%`,
        `${isEN ? 'Equity' : 'Équité'} : ${fmtNum(m.equity)} €  ·  ${isEN ? 'Capital gain' : 'Plus-value'} : ${m.capitalGain >= 0 ? '+' : ''}${fmtNum(m.capitalGain)} €`
      ];
      if (h.propertyType === 'locatif' && m.monthlyRent > 0) {
        lines.push(`${isEN ? 'Monthly rent' : 'Loyer'} : ${fmtNum(m.monthlyRent)} €  ·  ${isEN ? 'Cash-flow' : 'Cash-flow'} : ${m.monthlyCashflow >= 0 ? '+' : ''}${fmtNum(m.monthlyCashflow)} €/mois  ·  ${isEN ? 'Net yield' : 'Rentabilité nette'} : ${m.netYield.toFixed(2)}%`);
      }
      for (const line of lines) {
        if (y > 285) { doc.addPage(); y = margin; }
        doc.text(line, margin + 5, y);
        y += 4;
      }
      y += 3;
      doc.setFontSize(9);
    }
  }

  // Footer
  const total = doc.internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Alpha · ${new Date().toLocaleDateString(isEN ? 'en-US' : 'fr-FR')} · Page ${i}/${total}`, margin, 290);
  }

  const filename = `alpha-terminal-bilan-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
  return filename;
}
